# Generated by Django 3.1.3 on 2020-11-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_service', '0002_auto_20201127_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
