# Generated by Django 3.1.3 on 2020-11-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_service', '0003_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='order',
            field=models.ManyToManyField(default=False, null=True, to='bot_service.Order'),
        ),
    ]
