# Generated by Django 3.1.3 on 2020-12-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_service', '0004_auto_20201130_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='album',
        ),
        migrations.AlterField(
            model_name='user',
            name='order',
            field=models.ManyToManyField(to='bot_service.Order'),
        ),
    ]
